In [1]:
import numpy as np

In [14]:
ls = [2, 4, 5, 1, 4, 0]
arr = np.array(ls, dtype='object')
print(arr)
print(arr.dtype)

print(type(arr))

[2 4 5 1 4 0]
object
<class 'numpy.ndarray'>


In [19]:
arr1 = np.array([1, 2, 3, 4, 5, 3]).reshape(2, 3)
print(arr1)
arr2 = np.array([1, 2, 3, 4, 5, 3]).reshape(3, 2)
print(arr2)

out = np.matmul(arr1, arr2)
print(out)

[[1 2 3]
 [4 5 3]]
[[1 2]
 [3 4]
 [5 3]]
[[22 19]
 [34 37]]


In [33]:
arr3 = np.array([1, 2, 3, 4]).reshape(2, 2)
print(arr3)

print(np.product(arr3, axis=1))



[[1 2]
 [3 4]]
[ 2 12]
