In [13]:
# array vs list
import numpy as np
ls = [130, -120, 8, -2]
arr = np.array(ls, dtype='int8')

print('List', ls)
print('Array', arr)


List [130, -120, 8, -2]
Array [-126 -120    8   -2]


In [35]:
# ndmin
ls = [[[[20, 3], 10, 22], [100, 200, 30]], [[5, 10], [4,0]]]
out = ls[0][0][0][0]
print(out)

20


In [23]:
# 3 x 3
import numpy as np
ls1 = [[2, 4, 5], [2, 19, 0], [1, 1, 0]]
ls2 = [[0, 0, 1], [2, 1, 5], [2, 5, 3]]
arr1 = np.array(ls1)
arr2 = np.array(ls2)
out = np.add(arr1, arr2)
print(out)


[[ 2  4  6]
 [ 4 20  5]
 [ 3  6  3]]


In [34]:
# array vs list
import numpy as np
ls = [0, 128, 129]
arr = np.array(ls, dtype='int8')

print('List', ls)
print('Array', arr)

List [0, 128, 129]
Array [   0 -128 -127]


In [48]:
# ls 
arr = np.array([1, 3, 5, 2, 5, 2])
arr.shape = 3, 2
print(arr)

[[1 3]
 [5 2]
 [5 2]]


In [51]:
arr1 = np.array([[2, 4, 5], [3, 1, 0]])
arr2 = np.array([[2, 4, 4], [1, 1, 0], [2, 7, 8]])
if arr1.shape[1] == arr2.shape[0]:
    out = np.dot(arr1, arr2)
    print(out)
else:
    print('Shape is not valid for Matrix Multiplication')

[[18 47 48]
 [ 7 13 12]]


In [8]:
# list vs array
import numpy as np
ls = [20, 4, 56, 7, 8, 900]
arr = np.array(ls, dtype='int8')
print(ls)
print(arr.ndim)

[20, 4, 56, 7, 8, 900]
1


In [22]:
ls = [3, 4, 45, 4, 5, 6,2]
out = np.array(ls)
print(out)

[ 3  4 45  4  5  6  2]


In [27]:
out.shape[1]

7