In [1]:
# input section
import numpy as np
ls = list(map(eval, input().split()))

arr = np.array(ls, dtype=float)
# out = np.flip(arr)
print(arr[::-1])

[23. -3.  6.  4.  3.]


In [2]:
# task 2
ls = list(map(eval, input().split()))
ar = np.array(ls)
# ar.shape = 3,3
print(ar.reshape(3, 3))

[[3 4 5]
 [3 0 5]
 [6 3 4]]


In [6]:
# task 3
import numpy as np
a,b = list(map(int,input().split()))
print(np.eye(a,b))

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [ ]:
r, c = map(int, input('Enter R X C ').split())
arr1 = list(map(int, input().split()))
arr2 = list(map(int, input().split()))
arr1 = np.array(arr1).reshape(r, c)
arr2 = np.array(arr2).reshape(r, c)

# output
print(arr1 + arr2)


In [11]:
out = np.arange(1, 13.0).reshape(4, 3)
print(out)

[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]]
