In [ ]:
# functions in Numpy 

In [8]:
# array(): convert the list or ordinary array to numpy array
# syntax array(object, dtype=None, ndmin=0)
import numpy as np
ls = [3, 5, 7, 8, 4, 6]
out = np.array(ls)
out.shape = 2, 3
# out2 = out.reshape(2, 3)
print(out)
# print('\n', out2)

[[3 5 7]
 [8 4 6]]


In [16]:
# arange(start, stop, step)
import numpy as np
ls = np.arange(1, 13).reshape(4, 3)
print(ls)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [22]:
# addition of two matrix
import numpy as np
m1 = np.arange(1, 13).reshape(3, 4)
m2 = np.arange(5, 17).reshape(3, 4)
print('Matrix1')
print(m1)
print('\nMatrix2')
print(m2)

# addition of two matrix 
if m1.shape == m2.shape:
    out = np.add(m1, m2)

    print('\nAddition')
    print(out)
else:
    print('Shape is not valid for Addition')


Matrix1
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Matrix2
[[ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

Addition
[[ 6  8 10 12]
 [14 16 18 20]
 [22 24 26 28]]


In [30]:
# multiplication 
import numpy as np
m1 = np.arange(1, 13).reshape(3, 4)
m2 = np.arange(5, 17).reshape(4, 3)
print('Matrix1')
print(m1)
print('\nMatrix2')
print(m2)

# Matrix Multiplication of two matrix 
if m1.shape[1] == m2.shape[0]:
    out = np.dot(m1, m2)

    print('\nMultiplication')
    print(out)
else:
    print('Shape is not valid for Matrix Multiplication')


Matrix1
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Matrix2
[[ 5  6  7]
 [ 8  9 10]
 [11 12 13]
 [14 15 16]]

Multiplication
[[110 120 130]
 [262 288 314]
 [414 456 498]]


In [40]:
out = np.eye(4)
print(out)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [33]:
m1.shape[1]

4

In [28]:
print(m1)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [53]:
# numpy module
# a = array(object, dtype, ndmin=0)
import numpy as np
ls = [129, 10, 7, -130, 256]
print('list', ls)
out = np.array(ls, dtype='int8' )
print('Array', out)


list [129, 10, 7, -130, 256]
Array [-127   10    7  126    0]


In [15]:
# array(object, dtype=None, ndmin=0)
import numpy as np
# lst1 = [[3, 5, 7], [3, 6, 0]]
# lst2 = [[4, 6, 7], [2, 5, 0], [1, 2, 3]]

lst1 = eval(input())
lst2 = eval(input())

arr1 = np.array(lst1)
arr2 = np.array(lst2)

# Multiplication of two matrix
if arr1.shape[1] == arr2.shape[0]:
    out = np.dot(arr1, arr2)

    print('Matrix1')
    print(arr1)
    print('\nMatrix2')
    print(arr2)
    print('\nMatrix Multiplication')
    print(out)
else:
    print('Shape is not valid for Matrix Multiplication')

Matrix1
[[3 5 7]
 [3 6 0]]

Matrix2
[[4 6 7]
 [2 5 0]
 [1 2 3]]

Matrix Multiplication
[[29 57 42]
 [24 48 21]]


In [3]:
# zeros((r, c))
import numpy as np
out = np.zeros((3, 6))
print(out)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [4]:
# ones((r, c))
import numpy as np
out = np.ones((3, 6))
print(out)

[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]


In [9]:
# eye(r, c)
import numpy as np
out = np.eye(4)
print(out)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
